# Generated by Django 2.0.5 on 2018-08-12 20:36

from django.db import migrations, models
import predictor.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('file_name', models.FileField(upload_to=predictor.models.UserInput.k)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
